-- Table: task4.job;

-- DROP TABLE task4.job;

CREATE TABLE IF NOT EXISTS task4.job (
    job_id BIGSERIAL NOT NULL,
    CONSTRAINT pk_task4_job_job_id PRIMARY KEY (job_id)
);

ALTER TABLE task4.job
ADD COLUMN IF NOT EXISTS job_name TEXT,

ADD COLUMN IF NOT EXISTS created_on TIMESTAMP WITH TIME ZONE DEFAULT now(),
ADD COLUMN IF NOT EXISTS created_by BIGINT NOT NULL,
ADD COLUMN IF NOT EXISTS modified_on TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS modified_by BIGINT,
ADD COLUMN IF NOT EXISTS deleted_on TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS deleted_by BIGINT,
ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;